version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gostack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
#   web:
#     build: .
#     volumes:
#       - .:/code
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#     restart: always
